
#It's recommended to edit the config BEFORE you start up Minecraft. While most configs will work just fine while changed ingame, some require a restart to work properly.
#This category holds general values that will mostly be customized by most.
["Starting Configurations"]
	#This value modifies how many hearts you'll start at in a world. 2 would mean 1 extra heart, -2 would mean 1 less heart. If you have lives enabled, you'll gain a life when you get max hearts double your starting hearts. EX: If 3 hearts is your starting value, you'll gain a life if you get 3 more hearts. 
	#Range: > -19
	"Starting HitPoint Difference:" = 0
	#This values modifies the amount of hit points that should be lost when you die. The same also applies when you gain max health from lifestealing. 2 hit points = 1 health.
	#Range: > 1
	"Amount of HitPoints/Health Lost/Given Upon Death/Kill:" = 2
	#In multiplayer, this value determines whether heads spawn or not when a player dies. NOTE: In singleplayer, this value is always false.
	"Players Spawn Their Head Upon Death:" = true
	#In multiplayer, this value decides whether or not a player gets banned when they lose all hearts. If this value is false, they will go into spectator mode. This value does NOT affect singleplayer, you'll always go into spectator.
	"Players get Banned Upon Losing All Hearts:" = true
	#Any time the player dies, they will drop a Heart Crystal. The config that disables Unnatural Heart Crystals will not affect this.
	"Players Drop Heart Crystals When Killed:" = false

#This category is for how players should lose hearts. If you want players to not be able to lose hearts at all, disable all the config options below.
["Losing Hearts"]
	#When this is true, you will lose hearts when killed by a player.
	"Lose Hearts When Killed By a Player:" = true
	#When this is true, you will lose hearts when killed by a mob.
	"Lose Hearts When Killed By a Mob:" = true
	#When this is true, you will lose hearts when killed by the environment.
	"Lose Hearts When Killed By the Environment:" = true

#This category is the configuration for items and enchantments in this mod
["Items and Blocks"]

	["Items and Blocks"."Heart Cores"]
		#Heart Cores can heal on default 25% of your health if right clicked. This value determines if they should be disabled.
		"Disable Heart Cores:" = false
		#The percentage of max health a heart core should heal when used.
		#Range: 0.01 ~ 1.0
		"Percentage of max Health Heart Core Heals" = 0.33
		#If this option is true, a player cannot eat heart cores if they are already at their max health.
		"Prevent Players From Using Heart Cores If At Max Health:" = true
		#If this value is true, right clicking the heart core instantly uses it rather than you eating it.
		"Instantly use Heart Cores:" = false

	["Items and Blocks"."Heart Crystals"]
		#Heart Crystals increase the max amount of hearts you get when eaten, this value determines whether they are enabled or not. This will NOT affect Unnatural Heart Crystals.
		"Disable Heart Crystals:" = false
		#Disables Unnatural Heart Crystals. Unnatural Heart Crystals are achieved by using the withdraw command.
		"Disable Unnatural Heart Crystals:" = false
		#This is the amount of hit points a Heart Crystal should give when used. 2 HitPoints = 1 Heart, 3 = 1.5 Heart.
		#Range: > 1
		"Amount of HitPoints Heart Crystal Permanently Gives:" = 2
		#If a max is set for the amount of hearts you can get, this option when true, makes it so players can't eat heart crystals if they're already at the max.
		"Prevent Players From Using Heart Crystals If At Max Hearts:" = true
		#If this value is true, right clicking the heart crystal instantly uses it rather than you eating it.
		"Instantly use Heart Crystals:" = false

	["Items and Blocks"."Revive Crystals"]
		#This value determines whether or not revive crystals are disabled. If you're in singleplayer, this value is always true.
		"Disable Revive Crystals:" = false
		#When a player is revived, this value determines whether or not a chat message will be sent indicating they have been brought back from the dead.
		"Silently Revive Players:" = false
		#When a player is revived, lightning will strike the head from above for dramatic effect. This value can be used to disable this effect.
		"Disable Lightning Effect:" = false
		#When a player is revived, they get bonus effects such as regeneration and resistance. This value determines if they are disabled or not. It's recommended to keep this on if you are keeping the lightning effect above.
		"Disable Status Effects:" = false
		#If you want revived players to start off with a different heart difference, enable this value and configure the amount you'd like below
		"Use a Custom Heart Difference for Revived Players:" = false
		#This is applied the same way StartingHeartDifference works, this is used instead of StartingHeartDifference if the configuration to use this value is enabled.
		#Range: > -19
		"Amount of Hitpoints Given When Revived:" = 0

	["Items and Blocks"."Revive Heads"]
		#When this value is true, Revive Heads are indestructible! WARNING: This config is quite destructive, THE BLOCK IS LITERALLY INDESTRUCTIBLE. NOTHING (and I mean nothing!) can DESTROY IT. Not even /setblock or a person in creative.
		"Indestructible Revive Heads:" = false

#This category is everything related to life stealing from someone.
["Lifesteal Related"]
	#This makes it so you can't gain hearts from killing other players. THIS DOESN'T AFFECT LOSING HEARTS.
	"Disable Lifesteal:" = false
	#This value determines if a player should still earn hearts from a player they killed even if the player doesn't have hearts to spare. EX: MinimumHeartHave
	"Players Gain Hearts From No Heart Players:" = false

#This category will hold the maximums for certain values
[Maximums]
	#This value makes a limit SET after your Starting HitPoint Difference for how many hit points/hearts a player can get. 2 hit points = 1 heart. Set this to less than 0 to disable the feature.
	#Range: > -1
	"Maximum Amount of Hitpoints a Player can get:" = -1
	#This value makes a limit set on how many hit points/hearts a player can lose, this value is actually set depending on the Starting Health Difference. EX: Starting Health Difference - MinimumHeartHave. Set this to less than 0 to disable the feature.
	#Range: > -1
	"Maximum Amount Of Hitpoints a Player can Lose:" = -1
	#When a player has reached max hearts or attempt to go higher than the max, if this value is true, a message will let them know indicating they cannot go higher.
	"Tell Players if They Have Reached max Hearts:" = true
	#This value determines if a killed person should drop a heart crystal when the killer has max hearts. NOTE: This requires the MaximumHearts config to be enabled.
	"Players Drop Heart Crystals When Killer has Max" = false

#This category holds values related to commands. Permission Levels range from 0 to 4, 0: Everyone, 1: Moderators, 2: Gamemasters, 3: Admins, 4: Owners
[Commands]
	#This just makes it so when an admin changed a person's hitpoints, this value would determine if the game should tell the person in chat that their hitpoints was changed.
	"Tell Players if Their HitPoint Difference Changed:" = true

	[Commands.Withdrawing]
		#This value determines the advancement used to unlock withdrawing. You would find the advancement you want to use by using the ID of the advancement which is found with the /advancement command. If the value is empty, withdraw will be unlocked automatically.
		"The Advancement Needed to Unlock Withdrawing:" = "lifesteal:get_heart_crystal"
		#This value determines what text will pop up when a player hasn't unlocked withdrawing. If this value is empty, no text will pop up.
		"The Text Shown When Withdrawing Isn't Unlocked:" = "You need to at least have gotten one heart crystal in this world to withdraw"
		#Range: 0 ~ 4
		"Permission Level:" = 0

	[Commands.Set-Hitpoints]
		#Range: 0 ~ 4
		"Permission Level:" = 2

	[Commands.Get-Hitpoints]
		#Range: 0 ~ 4
		"Permission Level:" = 2

#This category holds values that don't fit in other categories OR are not made for gameplay usage.
["Misc/Fun"]
	#When this is false, you can only gain hearts from killing players. Otherwise, any mob will give you hearts.
	"Killing any Mobs Gives Hearts:" = false

